### ISSUE TITLE
Wrong request in setup.py

### ISSUE THREAD

**Issue by ertwro** [lebaston100/MIDItoOBS#11]
Hi. In setup.py the requests for StartRecording and StopRecording are wrong. They send instead StartStreaming and StopStreaming respectively.

BTW, is there a way to ignore the speed of the keyboard? I've noticed that if the speed is too slow it flickers due to sending de signal twice. I can't use the toggle options since they register press and release independently.

**Comment by lebaston100** [comment]
Thanks. Just looking into the code i can see that it's wrong. I will fix that shortly.

Can you explain in a little more detail what you mean with the "keyboard speed"?

**Comment by lebaston100** [comment]
Should be fixed with https://github.com/lebaston100/MIDItoOBS/commit/8d180566bd5dcc614418bf4894dac06b60205e24
