### ISSUE TITLE
How to support multiple devices?

### ISSUE THREAD

**Issue by gbraad** [lebaston100/MIDItoOBS#12]
For instance, I have a nanoPAD2 which I use to switch scenes with, but I would also like to use the nanoKONTROL2 to control the audio inputs with the faders. Perhaps, having even two nanoPAD2s it would be possible to easily switch between 32 scenes this way.

in code only one device is opened:

https://github.com/lebaston100/MIDItoOBS/blob/8d180566bd5dcc614418bf4894dac06b60205e24/main.py#L72

but it is possible to run `setup.py` multiple times which also creates multiple `"type": "device"` entries, however none of the commands are bound to a specific device.

Suggestions are welcome... such as merging midi devices to represent itself as a single 'virtual' device?

**Comment by lebaston100** [comment]
So the most basic way to do this, is to just have 2 Instances running with different config files. Because of how it loads the config, if you have 2 different folders each with the setup, main and the config file, you can have multiple instances running that do different stuff.
As for native integration this something i could add without a lot of work.

**Comment by gbraad** [comment]
Sounds good. Will use the suggested workaround for the moment.

**Comment by gbraad** [comment]
One of the easier fixes would be to make

https://github.com/lebaston100/MIDItoOBS/blob/8d180566bd5dcc614418bf4894dac06b60205e24/setup.py#L10

and 

https://github.com/lebaston100/MIDItoOBS/blob/8d180566bd5dcc614418bf4894dac06b60205e24/main.py#L48
https://github.com/lebaston100/MIDItoOBS/blob/8d180566bd5dcc614418bf4894dac06b60205e24/main.py#L266-L268

to allow a configurable `config.json` to be loaded. At the moment, the `MidiHandler` uses default parameter values. This way, alhough not super elegant yet, it is possible to run multiple instances of the script for each configured device. WDYT? Note: however does not enforce a single `device` entry in the configuration file.

**Comment by lebaston100** [comment]
I'll be doing some maintenance work when obs-websocket 4.6 is released. I will have a deeper look in how i can implement that.
With multiple input devices there would need to be a flag for every command to which controller it belongs.
I will leave this open for now. Feel free do add some more ideas or even send a pull request. You seem to be a much better programmer then me. Everything on my Github is just stuff i hacked together mostly for myself.

**Comment by gbraad** [comment]
> to which controller it belongs

I also concluded this. I'll hack up a simple workaround for the moment and try to push a PR

> when obs-websocket 4.6 is released

Any expected changes ?

> better programmer then me

Nonsense! Same here for a lot of stuff as I just do not have the time. Wish I could spend more on OSC and Midi stuff.

**Comment by lebaston100** [comment]
> Any expected changes ?

A lot of underlying code was changed, a lot of bugs fixed and there were some breaking changes in 4.5. that i don't want to invest the time into when i don't what will break with 4.6. And i want to maybe add the new requests that come with 4.5 and 4.6.

**Comment by gbraad** [comment]
As a temporary workaround I override the `config.json` based on the argument value. This way not much needed to be modified:

https://github.com/gbraad/MIDItoOBS/commit/84152933bfba4984fac80ddd209415c489cd2a57#diff-5bc02cefb3ea9e27f1a6776eabd1935dR26

and: 

https://github.com/gbraad/MIDItoOBS/commit/84152933bfba4984fac80ddd209415c489cd2a57#diff-2eeaed663bd0d25b7e608891384b7298R11

Note: the rest of this commit deals with convering from dos line endings to unix... else the top `sh-bang #!` does not work.

**Comment by lebaston100** [comment]
With 4.6.0 out now and the 4.6.1 hotfix after my bugreport i hope to start working on this in the near future.

**Comment by Darkace1337** [comment]
bump Just as a Plus 1 for this feature to be added

**Comment by lebaston100** [comment]
Can't promise any timeline, this might take months to be published, but spoiler:
![image](https://user-images.githubusercontent.com/26111114/64372997-cd19db00-d022-11e9-9f23-c8c76df56179.png)

**Comment by lebaston100** [comment]
Implemented with https://github.com/lebaston100/MIDItoOBS/commit/d1a646b8f14f1fc63d4b6fd1b539869f40f32ad6

**Comment by gbraad** [comment]
@lebaston100 thanks. will test soon. Also good to see the `requirements.txt` doing there now ;-)

**Comment by lebaston100** [comment]
@gbraad i hope the requirements.txt works as intended. Maybe when you do your testing you can test that too and let me know.
