### ISSUE TITLE
Behringer X-TOUCH MINI support

### ISSUE THREAD

**Issue by me-vlad** [lebaston100/MIDItoOBS#14]
Hi,
Please add to supported/tested devices Behringer X-TOUCH MINI controller.
All buttons, knobs, fader works fine with MIDItoOBS.
Thanks!

**Comment by lebaston100** [comment]
Thanks and done with https://github.com/lebaston100/MIDItoOBS/commit/ab27f5ade41e3be13fc1d8532ad2e94fa20d4926
