### ISSUE TITLE
Novation LaunchControl XL supported

### ISSUE THREAD

**Issue by lannonbr** [lebaston100/MIDItoOBS#21]
I can confirm the Novation LaunchControl XL works. Knobs, Faders, and Buttons all work as expected.

Really great tool @lebaston100!

**Comment by lebaston100** [comment]
Thanks. Which version did you test it with? (Or when did you download it)

**Comment by lannonbr** [comment]
I downloaded the Master branch as of Thursday the 23rd so I have been using the version right before that commit.
