### ISSUE TITLE
Studio Mode Crossfader

### ISSUE THREAD

**Issue by ludwigrauch** [lebaston100/MIDItoOBS#31]
Hi,

first of all, midi2obs is a wobderful piece of software! Thank you!
I got it to work with my apc mini. Now i am wondering if i can assign the crossfader in the studio mode to one of my faders on the apc.

Greetings from Germany
Ludwig

**Comment by lebaston100** [comment]
Hi. Thanks for the feedback. The t-bar control will be added as soon as obs-websocket 4.8.0 is released.

**Comment by ludwigrauch** [comment]
Very nice!

**Comment by lebaston100** [comment]
obs-websocket 4.8.0 was released today, but without the t-bar support because some work is needed on the obs side first. So we'll see. As soon as it's included it will be added to miditoobs.

**Comment by me-vlad** [comment]
T-Bar control  megred in to obs-websocket 
https://github.com/Palakis/obs-websocket/pull/439

**Comment by lebaston100** [comment]
MIDItoOBS integration is already done. Just waiting for the obs-websocket release. If you want to test the beta, you can download the files in the discord.

**Comment by lebaston100** [comment]
obs-websocket 4.9 is out which includes the T-bar feature so this is now available in miditoobs together with a bunch of other new requests.
