### ISSUE TITLE
SetOpacity

### ISSUE THREAD

**Issue by donmurdoc** [lebaston100/MIDItoOBS#33]
Hi, I tried seting up a knob to control opacity.
But when I run setup.py, it doesn't give me that option. Only gives me up to gain filter.

**Comment by lebaston100** [comment]
I just tested the most recent master and can not replicate it.
Are you using the last release? If so you need to use the latest master ZIP: https://github.com/lebaston100/MIDItoOBS/archive/master.zip

**Comment by donmurdoc** [comment]
Hi, I thought I was, but I guess I wasn't.
Not, runing setup, I get the option for opacity, but even though I have a Color Correction filter, it says I don't.
Screen capture in the .gif

![output](https://user-images.githubusercontent.com/13877246/84057660-5da89180-a98e-11ea-9c70-49e67a088644.gif)

**Comment by lebaston100** [comment]
Oh i see, i though i explained it well enough in the readme, but you have to rename the filter to "miditoobs-opacity" for it to be recogniced.

**Comment by lebaston100** [comment]
I changed the wording for the error message, should make it more clear: https://github.com/lebaston100/MIDItoOBS/commit/4935ae604514612fcdae0a5b1bd7b6bcdbf6327c

**Comment by donmurdoc** [comment]
Excellent! now it works perfectly!

Does this apply too for audio gain filter ? Should I rename it "miditoobs-gain" ?

**Comment by lebaston100** [comment]
Awesome. No, this only applys to the Opacity change.
As per the readme "This will automatically default to the first gain filter found in a source!"
