### ISSUE TITLE
Gain Filter Adjustment Not Working

### ISSUE THREAD

**Issue by vulgerrity** [lebaston100/MIDItoOBS#35]
I've got a Korg nanoKontrol2 and I've tried setting multiple knobs to multiple audio sources and their gain filters for adjustment, and I can't get it to work.

**Comment by lebaston100** [comment]
Thanks for the report. I just tried to reproduce it but it works fine for me with the most recent master.
Since i can't replicate it i need more details.
What obs and obs-websocket version?
How does your config file look like?
Can you enable debug logging in the obs-websocket settings and then set it up from scratch and test it and get me that obs log file?
Is your controller set to factory defaults?

There are at least 2 people (mentioned in the readme) that successfully use the nanoKONTROL 2.

**Comment by vulgerrity** [comment]
Weird, so I just got home from work and there was an update for OBS available.  Installed the update, and now the gain knob is working.  So, I'm at a loss for words.  I'll still give you my relevant info:

OBS 26.0.2
Web Socket 4.8.0
It's working now, so idk if this will be helpful, but here's the config:

`{
    "devices": {
        "1": {
            "devicename": "nanoKONTROL2 0"
        }
    },
    "keys": {
        "2": {
            "msg_type": "control_change",
            "msgNoC": 0,
            "input_type": "fader",
            "scale_low": 0,
            "scale_high": 1,
            "action": "{\"request-type\": \"SetVolume\", \"message-id\" : \"1\", \"source\": \"L1_Spotify\", \"volume\": %s}",
            "cmd": "SetVolume",
            "deviceID": 1
        },
        "4": {
            "msg_type": "control_change",
            "msgNoC": 48,
            "input_type": "button",
            "action": "{\"request-type\": \"ToggleMute\", \"message-id\" : \"1\", \"source\": \"L1_Spotify\"}",
            "deviceID": 1,
            "bidirectional": false
        },
        "5": {
            "msg_type": "control_change",
            "msgNoC": 16,
            "input_type": "fader",
            "scale_low": -10,
            "scale_high": 10,
            "action": "{\"request-type\": \"SetSourceFilterSettings\", \"message-id\" : \"1\",\"sourceName\" : \"L1_Spotify\", \"filterName\": \"Gain\", \"filterSettings\": {\"db\": %s}}",
            "cmd": "SetGainFilter",
            "deviceID": 1
        },
        "6": {
            "msg_type": "control_change",
            "msgNoC": 7,
            "input_type": "fader",
            "scale_low": 500,
            "scale_high": 10000,
            "action": "{\"request-type\": \"SetTransitionDuration\", \"message-id\" : \"1\", \"duration\": %s}",
            "cmd": "SetTransitionDuration",
            "deviceID": 1
        },
        "7": {
            "msg_type": "control_change",
            "msgNoC": 1,
            "input_type": "fader",
            "scale_low": 0,
            "scale_high": 1,
            "action": "{\"request-type\": \"SetVolume\", \"message-id\" : \"1\", \"source\": \"L2_Discord\", \"volume\": %s}",
            "cmd": "SetVolume",
            "deviceID": 1
        },
        "8": {
            "msg_type": "control_change",
            "msgNoC": 17,
            "input_type": "fader",
            "scale_low": -10,
            "scale_high": 10,
            "action": "{\"request-type\": \"SetSourceFilterSettings\", \"message-id\" : \"1\",\"sourceName\" : \"L2_Discord\", \"filterName\": \"Gain\", \"filterSettings\": {\"db\": %s}}",
            "cmd": "SetGainFilter",
            "deviceID": 1
        },
        "9": {
            "msg_type": "control_change",
            "msgNoC": 2,
            "input_type": "fader",
            "scale_low": 0,
            "scale_high": 1,
            "action": "{\"request-type\": \"SetVolume\", \"message-id\" : \"1\", \"source\": \"L3_Zoom\", \"volume\": %s}",
            "cmd": "SetVolume",
            "deviceID": 1
        },
        "10": {
            "msg_type": "control_change",
            "msgNoC": 18,
            "input_type": "fader",
            "scale_low": -10,
            "scale_high": 10,
            "action": "{\"request-type\": \"SetSourceFilterSettings\", \"message-id\" : \"1\",\"sourceName\" : \"L3_Zoom\", \"filterName\": \"Gain\", \"filterSettings\": {\"db\": %s}}",
            "cmd": "SetGainFilter",
            "deviceID": 1
        },
        "11": {
            "msg_type": "control_change",
            "msgNoC": 64,
            "input_type": "button",
            "action": "{\"request-type\": \"SetSceneItemProperties\", \"message-id\" : \"1\", \"item\": \"L1_Spotify\", \"visible\": %s}",
            "request": "ToggleSourceVisibility",
            "target": "L1_Spotify",
            "deviceID": 1,
            "field2": ""
        }
    }
}`

**Comment by lebaston100** [comment]
Yea, config looks fine. Not sure if the obs updated messed with it. I was testing with 26.0.2.
