### ISSUE TITLE
SetAudioMonitor Just Returns, "You Selected SetAudioMonitor"

### ISSUE THREAD

**Issue by vulgerrity** [lebaston100/MIDItoOBS#37]
I saw a note that this has been fixed.  Is this still an in progress feature?

**Comment by lebaston100** [comment]
Yes, this should have be fixed a few month ago. Do you still have problems with it in the most recent version?

**Comment by vulgerrity** [comment]
Yes, I downloaded the master file yesterday, and I also tried 0.2.3.

**Comment by vulgerrity** [comment]
And I don't see the option in 0.2.1

**Comment by lebaston100** [comment]
I'm amazed that noone has noticed that until now. Well it's fixed now with https://github.com/lebaston100/MIDItoOBS/commit/08178a20cabee73c89e1c4e3c0aa7b1e1f493713

**Comment by vulgerrity** [comment]
Awesome!  Thank you!
