### ISSUE TITLE
Run on OBS startup

### ISSUE THREAD

**Issue by redfox2492** [lebaston100/MIDItoOBS#39]
Is there any possibility of this running automatically on OBS startup? I've been messing around a bunch with LUA scripting to see, and have it so that a script runs it, but then OBS just gets hung up because it is waiting for the script to end, and we need it to keep running. Any ideas?

**Comment by lebaston100** [comment]
Hi. You need to make sure that whatever you use in lua to run the process just spawns the proces and doesn't wait for it.
I have no diea how that works in lua but a short google search found me something in the io.popen direction.

**Comment by lebaston100** [comment]
I'll close this in the meantime, feel free to add more comments if you have any.

**Comment by redfox2492** [comment]
We now have this working, after modifying a lua script to run a command when a scene is active. Our script(linked below as a text file, as apparently you can't attach lua scripts, so if anyone wants to use, the extension can just be changed) runs the command once OBS is loaded, as well as whenever a scene (selected in the properties) is set to preview. The command I used is:
```
cd {your file path to the folder where MIDItoOBS is stored} &&  start /min RunMain.bat
```
the start /min runs it minimized, because otherwise it opens on top of OBS which is annoying. I just made a scene called "Refresh MIDI Controller", which can be run if an operator ever needs to refresh the script for some reason.



[runMIDI.txt](https://github.com/lebaston100/MIDItoOBS/files/5659771/runMIDI.txt)

**Comment by lebaston100** [comment]
Awesome. Glad you got it working.
