### ISSUE TITLE
Problem with ToggleSourceVisibility when not "current" scene

### ISSUE THREAD

**Issue by dakahl** [lebaston100/MIDItoOBS#42]
The `ToggleSourceVisibility` function is not working if I want to use it on a diffrent scene than the `current` one.
Useful to toggle the visibility of overlays that are on one "Overlay_Scene" and that one gets included as source on all other scenes.

Error: "specified scene item doesn't exist".
The problem is, that the `scene-name` is not getting send on the `GetSceneItemProperties`.
I made a small workaround by using the `field2` property, and changed the Template.

`main.py` changes:
```
TEMPLATES = {
  "ToggleSourceVisibility": """{
    "request-type": "GetSceneItemProperties",
    "message-id": "%d",
    "item": "%s",
    "scene-name": "%s" # <--- add this line
}""",
```

`config.json` example that toggles the visibility of the Source `Text_Overlay` in the Scene `Overlay_Scene`:
```
        "8": {
            "msg_channel": 5,
            "msg_type": "note_on",
            "msgNoC": 51,
            "msgVoV": 127,
            "input_type": "button",
            "action": "{\"request-type\": \"SetSceneItemProperties\", \"message-id\" : \"1\", \"scene-name\": \"Overlay_Scene\", \"item\": \"Text_Overlay\", \"visible\": %s}",
            "request": "ToggleSourceVisibility",
            "target": "Text_Overlay",
            "field2": "Overlay_Scene",
            "deviceID": 1
        }
```

But with this workaround the `scene-name` is getting mandatory and therefore the `current`-Scene option is probably not working any more.
And of course I did not modify the `setup.py`. I just noticed that it adds only `scene` and not `scene-name` to the `"action"` property in a `ToggleSourceVisibility` request.

**Comment by lebaston100** [comment]
Thanks for the comment. i'll look into what i can do to better support this. Looks like a good feature to have.

**Comment by lebaston100** [comment]
Should be fixed with https://github.com/lebaston100/MIDItoOBS/commit/38f44ac67f47647cac34a23000c81136097c1db2
