### ISSUE TITLE
Request: Please Make command for SceneFilter

### ISSUE THREAD

**Issue by Aligatrox** [lebaston100/MIDItoOBS#44]
Hi i see what you doing, it's really nice but you made SourceFilter but can you madeSceneFilter (because use Move Source Plugin) 🥺

**Comment by lebaston100** [comment]
Hi there. I don't see a mention for "Scene Filters" anywhere, Scenes are Sources too so you can use them there too. A generic request to control plugin filters or internal filters that are not listed is in the works but won't be as user friendly as the rest of the listed obs filters.

**Comment by Aligatrox** [comment]
https://imgur.com/Mc6hrru

**Comment by lebaston100** [comment]
I think i see what you are trying to tell me. The Scenes are not listed in the selection menus even though it would work in theory. I'll take a look at it.

**Comment by Aligatrox** [comment]
If you make it, you will change all for me but just for use filter on Scene i always use Phone or i have launchpad 😥 and the must on the must if you can make it, it for programme color/Led for Launchpad

**Comment by lebaston100** [comment]
I'm currently trying and adding it to the requests that support it.
Unfortunately i will not be adding light outputs to miditoobs at this time.

**Comment by Aligatrox** [comment]
Okay Thanks you
Oh okay no problem ^^"

**Comment by lebaston100** [comment]
Done
