### ISSUE TITLE
Actions do not work

### ISSUE THREAD

**Issue by MayraTV** [lebaston100/MIDItoOBS#51]
I did everything thats said and the setup seemed to work perfectly but when I tried to use them on OBS, it didn't work out ... 
Do you know what could I have done wrong ?

**Comment by lebaston100** [comment]
With the amount of information not at all.
What is your config file, can you post that? Which obs and obs websocket version are you running?
Which MIDItoOBS version are you running?
What does the Console output show when you run the main.py?

**Comment by lebaston100** [comment]
Since there has been no response i'll close this for now. Feel free to comment again here.
