### ISSUE TITLE
"OBS disconnected/timed out/is not running." after receiving one input

### ISSUE THREAD

**Issue by dashemeth** [lebaston100/MIDItoOBS#6]
Hi lebaston100, and first of all thank you for your script.

I followed every steps from your installation guide, but i can't figure out why main.py is shutting down after recieving one input from my midi controller. 

OBS registers that input, the sceneswitch works (wich is good sign i guess), but the websocket link seems to be lost right after that.

I'm using :

OBS Studio 22.0.1
Websocket 4.4.0
Python 3.6.5

**Comment by lebaston100** [comment]
I just tried with the exact same setup and can not reproduce it. Can you dm me on Twitter or Instagram @lebaston100 so we can figure this out?

**Comment by lebaston100** [comment]
Please open a windows command prompt(if you are on windows) and paste these two commands and then try again if it works after that:
pip uninstall websocket-client
pip install websocket-client==0.49.0

Background: The current version of the lib is 0.51.0 which seems to have broken the connection part. This installs a little bit older version that is know to work properly.
