### ISSUE TITLE
Feature Request: Browser Reset Function

### ISSUE THREAD

**Issue by ptitodd** [lebaston100/MIDItoOBS#7]
Latest OBS-BrowserSource plugin doesn't reload when OBS-WS ResetSceneItem is issued anymore. But it does reload on browser URL change. So right now I can configure 2 midi buttons to pass different urls to reload a browser source scene item. So I've branched a copy of MIDItoOBS to start work on Making a "RefreshUrl" function. But after reviewing much of the code. I'm not sure where in the main.py script I can append a toggle string ('/?reload=0' and '/?reload=1') to the URL before sending the Websocket message. Any thoughts? Let me know if I need to clarify what I'm doing.

**Comment by ptitodd** [comment]
Actually, that's a great idea. I was looking at OBS_on_message():84 ToggleSourceVisibility. And that seemed (to me) like the most logical place to start and then I got lost in the array that gets pulled from the config.json. I am also adding in 'program_change' as the the LPD8 and wireless LPD8 have toggles that allow pads to send program change messages. They work like all the other messages just with no velocity or value and they drop in with any of the button functions.

**Comment by lebaston100** [comment]
So i took a look into the code and i'm going to implement it.
What would you preffer in terms of the string that get's added to the url. It should not break any website. I was thinking about something like "#<random string>" or maybe "?<random string>".
? could confuse a few sites that use post vars.

**Comment by ptitodd** [comment]
What if we just toggle the url between http://urlstring.dom/#refresh and http://urlstring.dom/

My only concern is that Anchor Tags ("#") shouldn't 'technically' reload a page, it reloads browser-source now, it may not reload in a future update (doubt it, but ya never know). But the queries ("?") do, in my opinion, represent a bigger potential for an issue as you've suggested. Could totally mess with some sites.

I like the keep it simple aspect of MIDItoOBS so I don't think it's necessary to let the user choose. We can always update the script if OBS makes a dramatic change.

**Comment by lebaston100** [comment]
Ok so then we'll use # for now. Give me a few days (maybe into the weekend) and i'll push it as soon as it works.
If someone has a problem with the #, they can just open an issue and i can tell them to change the symbol inside the code that should be enough for now.

**Comment by lebaston100** [comment]
So i added it in https://github.com/lebaston100/MIDItoOBS/commit/36552d518c990190f38d3dd038c9d6bc145c8eae

**Comment by ptitodd** [comment]
haven't had an opportunity to test it. but I can open a new issue if it's not working, Thanks for the addition
